apiVersion: v1
kind: Pod
metadata:
  name: average-temperature
spec:
  containers:
  - name: average-temperature
    image: fhp/avg_temperature_sensor:0.0.1
    imagePullPolicy: IfNotPresent
  nodeSelector:
    extra.resources.fhp/embserve: "true"
    # kubernetes.io/hostname: labnuc01-b1-node3
  tolerations:
  - key: "fita.fhp.pt/type"
    operator: "Equal"
    value: "far-edge"
    effect: "NoSchedule"