apiVersion: v1
kind: Pod
metadata:
  name: temperature-1
spec:
  containers:
  - name: temperature-1
    image: fhp/temperature_sensor:0.0.2
    imagePullPolicy: IfNotPresent
  nodeSelector:
    extra.resources.fhp/embserve: "true"
    extra.resources.fhp/temperature_sensor: "true"
    # kubernetes.io/hostname: labnuc01-b1-node1
  tolerations:
  - key: "fita.fhp.pt/type"
    operator: "Equal"
    value: "far-edge"
    effect: "NoSchedule"
