nameOverride: ''
fullnameOverride: ''
image:
  repository: harbor.nbfc.io/mlsysops/fita/far-edge-connection-provisioner
  pullPolicy: Always
  tag: 0.0.1
imagePullSecrets: []
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
role:
  extraRules: []
clusterRole:
  extraRules: []
mqttBroker:
  host: ''
  port: 1883
podAnnotations: {}
podLabels: {}
podSecurityContext:
  fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
resources: {}
livenessProbe: {}
readinessProbe: {}
nodeSelector: {}
tolerations: []
affinity: {}
